#ifndef __hmi_H__
#define __hmi_H__
#include "user.h"
void title_bar();
void button1(int ,int ,int ,int);
void info_bar(int x1,int y1,int x2,int y2);
void cnt_frm(int *);
void input_frm(int ,int ,int ,int);
void shut(int ,int);
void Rshut(int x,int y);
void _return(int ,int); 
void _Breturn(int x,int y);
int Pro_bar(int al_len,int x1,int x2,int y,int percent);
void op_window(int ,int ,int ,int);
void choose_window(int ,int);
void op_window1(int ,int ,int ,int );
void button2(int ,int ,int ,int );
void my_order(void);
void identity(void); 
void my_account();
void add_identity(void);
void add_info();
void settings(void);
void time_table(void);
void message(void);
void manage(void);
void look(void);
void about(void);
void feedback(void);
void regist(void);
void log_in(void);
void _help();
void book(void);
void data(void);
void NewData(void);
void DeleteData();
void NewKT(int page,int modify);
void NewG(int page,int modify);
void NewD(int page,int modify);
void NewZ();
void ModifyData();
void more(int page,char train);
void Adv_choose();
void warning_overflow(int x,int y);
void start_book(int flag);
int DEstbook(USER *user);
void pay();
void pay_method();
void paybypassword();
void PayByQR();
void pay_OK();
void ticket(int x,int y);
void Password();
void success_hint();
void theme();
void my_profile();
void success_submit();
void clear_data();
#endif
